<html>
<head>
<title>Custom Error Handling in JavaScript</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">JavaScript中的自定义错误处理</h1>
<blockquote>原文：<a href="https://medium.com/nerd-for-tech/custom-error-handling-in-javascript-a3ce12aa38ff?source=collection_archive---------8-----------------------#2021-07-02">https://medium.com/nerd-for-tech/custom-error-handling-in-javascript-a3ce12aa38ff?source=collection_archive---------8-----------------------#2021-07-02</a></blockquote><div><div class="ds gw gx gy gz ha"/><div class="hb hc hd he hf"><div class=""/><figure class="ev ex ig ih ii ij er es paragraph-image"><div role="button" tabindex="0" class="ik il di im bf in"><div class="er es if"><img src="../Images/d4bd3203fed534b2306ae1c3dfde7e36.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*fpRBL2t0CSWb6mepNrJFGA.jpeg"/></div></div><figcaption class="iq ir et er es is it bd b be z dx translated">照片经由<a class="ae iu" href="https://unsplash.com/@john_matychuk" rel="noopener ugc nofollow" target="_blank">约翰·马特丘克</a>经由<a class="ae iu" href="https://unsplash.com/photos/dJdcb11aboQ" rel="noopener ugc nofollow" target="_blank">unsplash.com</a></figcaption></figure><p id="4930" class="pw-post-body-paragraph iv iw hi ix b iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn jo jp jq jr js hb bi translated">编写在正常操作条件下工作的代码是一项很好的技能。编写即使出错也能工作的代码更好。在代码中，出错的方式有很多种。</p><p id="fc11" class="pw-post-body-paragraph iv iw hi ix b iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn jo jp jq jr js hb bi translated">例如，当代码本身有问题时，可能传递给函数的参数的类型或数量是错误的。或者有时浏览器不兼容会导致问题。其他时候，表单中的用户输入可能是罪魁祸首。</p><p id="fdcf" class="pw-post-body-paragraph iv iw hi ix b iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn jo jp jq jr js hb bi translated">不管它们是如何发生的，了解如何防止它们破坏你的程序是很重要的。在这篇文章中，我将简要解释主要的JavaScript错误类型，更重要的是，向您展示JavaScript允许我们创建自己的自定义错误的一些方法。</p></div><div class="ab cl jt ju gp jv" role="separator"><span class="jw bw bk jx jy jz"/><span class="jw bw bk jx jy jz"/><span class="jw bw bk jx jy"/></div><div class="hb hc hd he hf"><p id="bc66" class="pw-post-body-paragraph iv iw hi ix b iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn jo jp jq jr js hb bi translated">JavaScript中有九种错误类型，包括一般错误。另外八个是EvalError、RangeError、ReferenceError、SyntaxError、TypeError、URIError、AggregateError和InternalError。根据我的经验，我看到的最常见的错误是语法和类型错误，通常是在开发过程中遇到的。</p><p id="6d0a" class="pw-post-body-paragraph iv iw hi ix b iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn jo jp jq jr js hb bi translated"><em class="ka">有关这些错误含义的详细信息，请参见MDN页面上的</em> <a class="ae iu" href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error" rel="noopener ugc nofollow" target="_blank"> <em class="ka">错误</em> </a> <em class="ka">。</em></p><p id="4889" class="pw-post-body-paragraph iv iw hi ix b iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn jo jp jq jr js hb bi translated">这些核心错误类型都是对象，令人惊讶的是JavaScript中的一切都是对象，并且共享几个相同的实例方法。最常见的两种方法是<code class="du kb kc kd ke b">name()</code>和<code class="du kb kc kd ke b">message()</code>。</p><p id="d46f" class="pw-post-body-paragraph iv iw hi ix b iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn jo jp jq jr js hb bi translated">关于错误的背景已经说得够多了，让我们来看看好东西，自定义错误处理！</p></div><div class="ab cl jt ju gp jv" role="separator"><span class="jw bw bk jx jy jz"/><span class="jw bw bk jx jy jz"/><span class="jw bw bk jx jy"/></div><div class="hb hc hd he hf"><h1 id="4182" class="kf kg hi bd kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc bi translated">试，扔，抓</h1><p id="a8e4" class="pw-post-body-paragraph iv iw hi ix b iy ld ja jb jc le je jf jg lf ji jj jk lg jm jn jo lh jq jr js hb bi translated">为了创建我们自己的错误，我们将希望串联使用<code class="du kb kc kd ke b">try</code>、<code class="du kb kc kd ke b">catch</code>语句。try语句允许您测试代码块中的错误，然后是catch语句，catch语句允许我们指定如何处理该错误，并允许我们的程序继续运行。</p><p id="946e" class="pw-post-body-paragraph iv iw hi ix b iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn jo jp jq jr js hb bi translated">在我们的try语句中，我们可以用任何我们想要的方式限定输入或代码，如果那些条件没有被满足，那么<code class="du kb kc kd ke b">throw</code>就是一个定制的异常。当抛出一个异常时，我们可以抛出一个简单的表达式，一个新的错误对象或者一个带有独特属性或实例方法的自定义错误对象。</p><p id="23d3" class="pw-post-body-paragraph iv iw hi ix b iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn jo jp jq jr js hb bi translated">我们来看一个简单的抛出表达式的例子。</p><pre class="li lj lk ll fd lm ke ln lo aw lp bi"><span id="6478" class="lq kg hi ke b fi lr ls l lt lu">1.  let x = 2<br/>2.  try { if ( x &lt; 5 ) {<br/>3.     throw 'Input number is too small' } <br/>4.  } catch(error) {<br/>5.     console.log(error) }</span><span id="1944" class="lq kg hi ke b fi lv ls l lt lu">// 'Input number is too small'</span></pre><p id="95cf" class="pw-post-body-paragraph iv iw hi ix b iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn jo jp jq jr js hb bi translated">这是向用户发送消息的一种简单方式。它可以用来抛出字符串，数字，布尔或对象。catch语句自动传递try语句中引发的错误的参数。如果没有抛出错误，则跳过catch语句。</p><p id="5e17" class="pw-post-body-paragraph iv iw hi ix b iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn jo jp jq jr js hb bi translated">抛出一个<code class="du kb kc kd ke b">new Error</code>需要一个消息的单一参数。对于相同的结果，前面的示例可以编写如下。new关键字表示新错误对象的构造函数。</p><pre class="li lj lk ll fd lm ke ln lo aw lp bi"><span id="6ba2" class="lq kg hi ke b fi lr ls l lt lu">1.  let x = 2<br/>2.  try { if ( x &lt; 5 ) {<br/>3.     throw new Error('Input number is too small') } <br/>4.  } catch(error) {<br/>5.     console.log(error.message) }</span><span id="3936" class="lq kg hi ke b fi lv ls l lt lu">// 'Input number is too small'</span></pre><p id="f1a5" class="pw-post-body-paragraph iv iw hi ix b iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn jo jp jq jr js hb bi translated">自定义错误处理的真正优点和优势是创建一个自定义错误对象(下面的第2–7行)。通过这样做，您可以传递参数，并根据需要创建尽可能多的有用属性或实例方法。请看下面的截图，我是如何使用一个自定义对象来处理我创建的简单输入框的错误的。我要检查的是输入字符串的第一个字母是否大写。</p><figure class="li lj lk ll fd ij er es paragraph-image"><div role="button" tabindex="0" class="ik il di im bf in"><div class="er es lw"><img src="../Images/8083a5ab24faf3eccab64c2a6a926ce4.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*xMwhW3Oak4LAYrjcOynQ9w.png"/></div></div></figure><p id="5068" class="pw-post-body-paragraph iv iw hi ix b iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn jo jp jq jr js hb bi translated">当我提交我的名字<code class="du kb kc kd ke b">david</code>时，它打印出我的自定义错误消息和我提供给DOM的输入。</p><figure class="li lj lk ll fd ij er es paragraph-image"><div role="button" tabindex="0" class="ik il di im bf in"><div class="er es lx"><img src="../Images/24724ac2c535b8e1b9939206dc29ab25.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/1*qAM1B7kwZMN440FR8kUiTA.gif"/></div></div></figure><p id="fe77" class="pw-post-body-paragraph iv iw hi ix b iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn jo jp jq jr js hb bi translated">这是一个非常简单的例子，说明了如何在JavaScript中创建自定义错误对象，但是您可以想象所有不同的用例。可能性实际上是无穷无尽的。</p><p id="e1a8" class="pw-post-body-paragraph iv iw hi ix b iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn jo jp jq jr js hb bi translated">你可以在我的GitHub <a class="ae iu" href="https://github.com/dpolcari18/custom-errors-blog" rel="noopener ugc nofollow" target="_blank">这里</a>看到最后一个例子的代码。如何使用try/catch语句在程序中处理错误和创建异常？请在下面的评论中告诉我！</p></div></div>    
</body>
</html>